from enum import Enum


class ListingsV2ProjectPropertyTypesType0Item(str, Enum):
    ACREAGESEMIRURAL = "acreageSemiRural"
    APARTMENTUNITFLAT = "apartmentUnitFlat"
    AQUACULTURE = "aquaculture"
    BLOCKOFUNITS = "blockOfUnits"
    CARSPACE = "carspace"
    CHICKENSHOP = "chickenShop"
    CROPPING = "cropping"
    DAIRYFARMING = "dairyFarming"
    DELICAFE = "deliCafe"
    DEVELOPMENTLAND = "developmentLand"
    DEVELOPMENTSITE = "developmentSite"
    DUPLEX = "duplex"
    EQUINE = "equine"
    FARM = "farm"
    FARMLET = "farmlet"
    FISHINGFORESTRY = "fishingForestry"
    GRAZING = "grazing"
    HOMEBASED = "homeBased"
    HORTICULTURE = "horticulture"
    HOTELLEISURE = "hotelLeisure"
    HOUSE = "house"
    INDUSTRIALWAREHOUSE = "industrialWarehouse"
    INTERNATIONAL = "international"
    IRRIGATIONSERVICES = "irrigationServices"
    LIVESTOCK = "livestock"
    MEDICALCONSULTING = "medicalConsulting"
    MIXEDFARMING = "mixedFarming"
    NEWAPARTMENTS = "newApartments"
    NEWHOMEDESIGNS = "newHomeDesigns"
    NEWHOUSELAND = "newHouseLand"
    NEWLAND = "newLand"
    OFFICES = "offices"
    ONLINEBUSINESS = "onlineBusiness"
    ORCHARD = "orchard"
    OTHER = "other"
    PARKINGCARSPACE = "parkingCarSpace"
    PENTHOUSE = "penthouse"
    RETAIL = "retail"
    RETIREMENT = "retirement"
    RURAL = "rural"
    RURALCOMMERCIALFARMING = "ruralCommercialFarming"
    RURALLIFESTYLE = "ruralLifestyle"
    SEAFOODSHOP = "seafoodShop"
    SEMIDETACHED = "semiDetached"
    SERVICEDOFFICES = "servicedOffices"
    SHOWROOMSBULKYGOODS = "showroomsBulkyGoods"
    SPECIALISTFARM = "specialistFarm"
    STUDIO = "studio"
    TERRACE = "terrace"
    TOWNHOUSE = "townhouse"
    UNKNOWN = "unknown"
    VACANTLAND = "vacantLand"
    VILLA = "villa"
    VITICULTURE = "viticulture"

    def __str__(self) -> str:
        return str(self.value)
